services:
  rabbitmq: 
    image: rabbitmq:3.9-management
    container_name: rabbit
    # command: --hostname rabbit1
    hostname: testrabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test123!
    volumes:
      - ./config/:/etc/rabbitmq/
      - ./data/:/var/lib/rabbitmq/
      # - ./home/:/opt/rabbitmq/
